name: Production Deploy

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - run: echo ${{ github.actor }}
      - uses: actions/checkout@v4
      - run: git push --force origin develop:main
